name: Build and push to docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PSW: ${{ secrets.DOCKERPASS }}
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Build with Maven
      run: mvn -B -DargLine="-Dspring.profiles.active=test" package --file pom.xml
      
    - name: Build docker image
      run: mvn docker:build        
      
    - name: Publish image to docker hub
      run: mvn -Ddocker.username=$DOCKER_USER -Ddocker.password=$DOCKER_PSW docker:push
